services:
  openstad-mysql:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-openstad-no-db}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - API_DB_NAME=${API_DB_NAME}
    command:
      - mysqld
      - --mysql_native_password=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      # - ./export.sql:/docker-entrypoint-initdb.d/99-export.sql
      - ./scripts/init-sql.sh:/docker-entrypoint-initdb.d/init-sql.sh
      - openstad-mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  openstad-redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 20s
      retries: 10

  openstad-mongo:
    image: mongo
    restart: always
    volumes:
      - openstad-mongo-data:/var/lib/mongo

  openstad-mailpit:
    image: axllent/mailpit:v1.15
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  openstad-mysql-data: {}
  openstad-mongo-data: {}
